spring.application.name=AccountA
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
  open-in-view: false